sonar.projectKey=taller-sast
sonar.projectName=Taller SAST - ESPAM Monorepo
sonar.sourceEncoding=UTF-8

sonar.sources=apps/auth-service/src,apps/products/src,apps/frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.tests=apps/auth-service/src,apps/products/src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=apps/auth-service/coverage/lcov.info,apps/products/coverage/lcov.info

sonar.qualitygate.wait=true
